version: '3.7'

services:
  database_ignite:
    image: postgres
    container_name: database_boilerplate
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=boilerplate
      - POSTGRES_PASSWORD=boilerplate
      - POSTGRES_DB=boilerplate
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: boilerplate
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links: 
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
